### ISSUE TITLE
 'TeViT is not in the models registry'

### ISSUE THREAD

**Issue by PoojanPanchal** [hustvl/TeViT#3]
Hi, I am trying to run this repo and i have followed all the steps mentioned in the description. 

While running the inference code, I am getting the following error. 
`python tools/test_vis.py configs/tevit/tevit_msgshift.py checkpoints/tevit_r50.pth
Traceback (most recent call last):
  File "tools/test_vis.py", line 130, in <module>
    main(args)
  File "tools/test_vis.py", line 53, in main
    cfg_options=args.cfg_options)
  File "/home/quidich/.virtualenvs/tevit/lib/python3.6/site-packages/mmdet/apis/inference.py", line 43, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "/home/quidich/.virtualenvs/tevit/lib/python3.6/site-packages/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/quidich/.virtualenvs/tevit/lib/python3.6/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/quidich/.virtualenvs/tevit/lib/python3.6/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/quidich/.virtualenvs/tevit/lib/python3.6/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'TeViT is not in the models registry'`

Kindly, could you guide me if I want to create a file that directly runs this algorithm on a video or set of images and provide an out in the form of images and json format which is saved in some folder?

**Comment by vealocia** [comment]
Hi, @PoojanPanchal!
In most cases, registry issues is caused by inappropriate ```mmdetection``` installtion. You can run ```python setup.py develop``` to install ```TeViT```. If you had installed other ```mmdetection``` based repo in your workspace before, these repos may be conflict to each other. You can use ```pip uninstall``` to uninstall the already installed mmdetection version and then reinstall the correct one!
Hope your ongoing research goes well!😁

**Comment by johannabar** [comment]
Hey, I had the same issue because I tried to install mmcv-full before doing the `python setup.py develop`.

What worked for me was: `pip uninstall mmcv` and `pip uninstall mmdet`, then `pip install mmcv==1.4.8` and finally cd into your cloned `TeViT/` directory and do `pip install .` to install the correct mmdet version.
