### ISSUE TITLE
About demo test

### ISSUE THREAD

**Issue by LuoYingzhao** [hustvl/TeViT#5]
Thanks for your excellent work.
For the test of image_demo.py(or video_demo.py) in /demo, use the demo.jpg(or demo.mp4) as input, there is a problem.
Could you please provide some advice? Looking forward to your reply.

1.
/TeViT/mmdet/apis/inference.py:50: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '

2.
Traceback (most recent call last):
  File "image_demo.py", line 65, in <module>
    main(args)
  File "image_demo.py", line 35, in main
    result = inference_detector(model, args.img)
  File "/TeViT/mmdet/apis/inference.py", line 137, in inference_detector
    data['img_metas'] = [img_metas.data[0] for img_metas in data['img_metas']]
TypeError: 'DataContainer' object is not iterable

File "video_demo.py", line 61, in <module>
    main()
  File "video_demo.py", line 47, in main
    result = inference_detector(model, frame)
  File "/TeViT/mmdet/apis/inference.py", line 137, in inference_detector
    data['img_metas'] = [img_metas.data[0] for img_metas in data['img_metas']]
TypeError: 'DataContainer' object is not iterable

**Comment by vealocia** [comment]
Hi, @LuoYingzhao ! Thanks for your interests in our work.
The demo script ```demo.py``` is provided by original ```mmdetection``` for 2D object detection and segmentation methods, TeViT maybe not compatible to this script.
If you want to visualize predictions from TeViT, I suggest you converting your test video into youtube-vis format, then get and visualize the predicted json file.
Hope this is helpful to you!
