### ISSUE TITLE
Ran out of input

### ISSUE THREAD

**Issue by assia855** [hustvl/TeViT#8]
Thanks for your work. I'm struggling for days with this error. Can you please provide some solutions to overcome it.

(base) root@78845bc2a82a:/mmdetection/Tevit# python tools/test_vis.py configs/tevit/tevit_msgshift.py  checkpoint/tevit_r50.pth
load checkpoint from local path: checkpoint/tevit_r50.pth
Traceback (most recent call last):
  File "tools/test_vis.py", line 137, in <module>
    main(args)
  File "tools/test_vis.py", line 54, in main
    cfg_options=args.cfg_options)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/apis/inference.py", line 45, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 581, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 520, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 285, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 302, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by vealocia** [comment]
Hi, @assia855! Thanks for your attention in our work.
It seems the error occurs when pytorch tries to load pre-trained weight, you can check if the pretrained weight is downloaded correctly.

**Comment by assia855** [comment]
Thanks for your feedback. Yes, I resolve this error by reloading the models now it's working fine. 
How can we test and visualize the mask on one image. I'm struggling with that. Thanks a lot.
